"""Self-contained HTML report render layer — the code half of the shared
report design (the other half is the DesignSync preview bundle; both consume
autogis/core/common/report_assets/report.css).

Pure stdlib. Escape-safe: only *_html-suffixed params accept caller-supplied
raw HTML; every other value is html.escape-d, and attribute contexts use
quote=True so a double-quote cannot break out of an attribute.
"""
from __future__ import annotations

import html
from importlib.resources import files
from typing import Callable, Optional, Sequence

TONES = frozenset({"ok", "warn", "bad", "info", "neutral"})


def _css() -> str:
    return files("autogis.core.common.report_assets").joinpath(
        "report.css").read_text(encoding="utf-8")


def _esc(v) -> str:
    return html.escape("" if v is None else str(v))


def _attr(v) -> str:
    return html.escape("" if v is None else str(v), quote=True)


def _tone_class(tone: Optional[str]) -> str:
    t = tone or "neutral"
    if t not in TONES:
        t = "neutral"
    return f"tone-{t}"


# Public aliases — the DesignSync generator (Task 7) and report tools (Task 4)
# consume these; keep the underscored names for internal call sites.
esc = _esc
attr = _attr


def css() -> str:
    """The canonical report stylesheet text (single source of truth)."""
    return _css()


def badge(text, tone: str = "neutral") -> str:
    return f'<span class="badge {_tone_class(tone)}">{_esc(text)}</span>'


def kpi_row(items: Sequence[tuple]) -> str:
    tiles = []
    for item in items:
        label, value = item[0], item[1]
        tone = item[2] if len(item) > 2 else "neutral"
        tiles.append(
            f'<div class="kpi {_tone_class(tone)}">'
            f'<div class="kpi-value">{_esc(value)}</div>'
            f'<div class="kpi-label">{_esc(label)}</div></div>'
        )
    return f'<div class="kpi-row">{"".join(tiles)}</div>'


def table(headers: Sequence, rows: Sequence[Sequence], *,
          tone_of: Optional[Callable[[int, int], Optional[str]]] = None) -> str:
    head = "".join(f"<th>{_esc(h)}</th>" for h in headers)
    body = []
    for i, row in enumerate(rows):
        cells = []
        for j, cell in enumerate(row):
            tone = tone_of(i, j) if tone_of else None
            cls = f' class="{_tone_class(tone)}"' if tone else ""
            cells.append(f"<td{cls}>{_esc(cell)}</td>")
        body.append(f"<tr>{''.join(cells)}</tr>")
    return (f'<table class="data"><thead><tr>{head}</tr></thead>'
            f'<tbody>{"".join(body)}</tbody></table>')


def card(title, body_html: str) -> str:
    return (f'<section class="card"><h3 class="card-title">{_esc(title)}</h3>'
            f'<div class="card-body">{body_html}</div></section>')


def section(heading, body_html: str) -> str:
    return (f'<section class="report-section"><h2>{_esc(heading)}</h2>'
            f'{body_html}</section>')


def photo_grid(images: Sequence[tuple]) -> str:
    figs = []
    for src, caption in images:
        figs.append(
            f'<figure class="photo"><img src="{_attr(src)}" '
            f'alt="{_attr(caption)}"/>'
            f'<figcaption>{_esc(caption)}</figcaption></figure>'
        )
    return f'<div class="photo-grid">{"".join(figs)}</div>'


def render_document(*, title, subtitle: str = "", meta: Optional[dict] = None,
                    sections: Sequence[str] = (), generated: str = "") -> str:
    subtitle_html = f'<p class="subtitle">{_esc(subtitle)}</p>' if subtitle else ""
    meta_html = ""
    if meta:
        items = "".join(
            f'<div class="meta-item"><span class="meta-k">{_esc(k)}</span>'
            f'<span class="meta-v">{_esc(v)}</span></div>'
            for k, v in meta.items()
        )
        meta_html = f'<div class="meta-strip">{items}</div>'
    footer = "Generated by AutoGIS" + (f" · {_esc(generated)}" if generated else "")
    return (
        "<!doctype html>\n"
        '<html lang="en"><head><meta charset="utf-8"/>'
        '<meta name="viewport" content="width=device-width, initial-scale=1"/>'
        f"<title>{_esc(title)}</title><style>{_css()}</style></head>"
        '<body><main class="report">'
        f'<header class="report-header"><h1>{_esc(title)}</h1>'
        f"{subtitle_html}{meta_html}</header>"
        f"{''.join(sections)}"
        f'<footer class="report-footer">{footer}</footer>'
        "</main></body></html>"
    )
